services:
  mcp-tools-agent:
    build:
      context: .
      dockerfile: Dockerfile
      #dockerfile: Dockerfile.dev
      args:
        - OSPREY_VERSION=v0.0.6
    tty: true          # Enable TTY
    stdin_open: true   # Keep stdin open
    environment:
      #TERM: xterm-256color
      MCP_SERVER: http://mcp-server:9090

    models:
      tools_model:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_TOOLS_MODEL
    depends_on:
      mcp-server:
        condition: service_started

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    
models:
  tools_model:
    model: hf.co/salesforce/llama-xlam-2-8b-fc-r-gguf:q4_k_m
