services:
  calc-agent:
    build:
      context: .
      #dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
      args:
        - OSPREY_VERSION=v0.1.0
    tty: true          # Enable TTY
    stdin_open: true   # Keep stdin open
    environment:
      #TERM: xterm-256color
      SYSTEM_INSTRUCTION: |
        You are a useful AI agent. 
        Tour name is bob.

      MCP_SERVER: http://mcp-server:9090

    models:
      chat_model:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL
      tools_model:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_TOOLS_MODEL
        
    depends_on:
      mcp-server:
        condition: service_started
  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    
models:
  chat_model:
    model: ai/qwen2.5:latest
  tools_model:
    #model: hf.co/salesforce/llama-xlam-2-8b-fc-r-gguf:q4_k_m
    #model: hf.co/salesforce/xlam-2-3b-fc-r-gguf:q4_k_s
    model: hf.co/menlo/lucy-128k-gguf:q4_k_m
